#!/usr/bin/env python3
"""
Fix GitHub Pages deployment issues.
The problem: https://fli-rpx.github.io/travel-website/cities/guangzhou.html returns 404
"""

import os
import shutil

def check_github_pages_structure():
    """Check if the website structure is correct for GitHub Pages."""
    
    print("=" * 70)
    print("🔧 GITHUB PAGES DEPLOYMENT FIX")
    print("=" * 70)
    
    website_dir = os.path.dirname(os.path.abspath(__file__))
    
    print("\n📁 Checking current structure...")
    
    # Check essential files
    essential_files = [
        "index.html",
        "cities/",
        "style.css"
    ]
    
    missing_files = []
    for file in essential_files:
        path = os.path.join(website_dir, file)
        if os.path.exists(path):
            print(f"✅ {file}")
        else:
            print(f"❌ {file} - MISSING")
            missing_files.append(file)
    
    # Check city pages
    cities_dir = os.path.join(website_dir, "cities")
    if os.path.exists(cities_dir):
        city_files = [f for f in os.listdir(cities_dir) if f.endswith('.html')]
        print(f"\n🏙️  City pages: {len(city_files)} files")
        
        # Check a few specific cities
        test_cities = ["guangzhou.html", "beijing.html", "shanghai.html"]
        for city in test_cities:
            city_path = os.path.join(cities_dir, city)
            if os.path.exists(city_path):
                print(f"✅ {city} exists")
            else:
                print(f"❌ {city} missing")
    
    return len(missing_files) == 0

def create_github_pages_config():
    """Create GitHub Pages configuration files."""
    
    print("\n📝 Creating GitHub Pages configuration...")
    
    website_dir = os.path.dirname(os.path.abspath(__file__))
    
    # 1. Create .nojekyll file (tells GitHub Pages not to use Jekyll)
    nojekyll_path = os.path.join(website_dir, ".nojekyll")
    with open(nojekyll_path, 'w') as f:
        f.write("")
    print(f"✅ Created: .nojekyll")
    
    # 2. Create CNAME file (if you have custom domain)
    # cname_path = os.path.join(website_dir, "CNAME")
    # with open(cname_path, 'w') as f:
    #     f.write("your-domain.com")
    # print(f"✅ Created: CNAME")
    
    # 3. Create proper .gitignore
    gitignore_content = """# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node_modules
node_modules/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# next.js build output
.next

# nuxt.js build output
.nuxt

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# Temporary folders
tmp/
temp/

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
env/
.venv/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Monitoring logs
*_monitor*.log
*_monitor*.txt
website_monitor_status.json
enhanced_monitor_status.json
monitor_config.json

# AI config (contains API keys)
ai_image_config.json

# Generated files
baidu_image_replacements.json
DEPLOYMENT_GUIDE.md
DEPLOY_NOW.md
cron_setup_instructions.txt
test_local.html
"""
    
    gitignore_path = os.path.join(website_dir, ".gitignore")
    with open(gitignore_path, 'w') as f:
        f.write(gitignore_content)
    print(f"✅ Created: .gitignore")
    
    # 4. Create README for GitHub
    readme_content = """# Travel Website

A modern travel website for Chinese cities with automated monitoring and AI image generation.

## Features

- 12 complete city pages (Beijing, Shanghai, Chengdu, Harbin, Chongqing, etc.)
- Automated monitoring system (runs every 10 minutes)
- AI image generation ready
- Self-improving capabilities
- Mobile responsive design
- Consistent styling across all pages

## Deployment

This site is deployed via GitHub Pages at: https://fli-rpx.github.io/travel-website/

## Monitoring System

The website includes an automated monitoring system that:
- Checks every 10 minutes for issues
- Verifies images, pages, and styling consistency
- Can auto-fix common problems
- Logs all activities

## City Pages

All city pages are located in the `cities/` directory:
- `beijing.html` - Beijing city page
- `shanghai.html` - Shanghai city page
- `chengdu.html` - Chengdu city page
- `harbin.html` - Harbin city page
- `chongqing.html` - Chongqing city page
- `wuxi.html` - Wuxi city page
- `qingdao.html` - Qingdao city page
- `xiamen.html` - Xiamen city page
- `nanjing.html` - Nanjing city page
- `shenzhen.html` - Shenzhen city page
- `guangzhou.html` - Guangzhou city page
- `hongkong.html` - Hong Kong city page

## Development

To run locally:
```bash
python3 -m http.server 8000
```

Then open: http://localhost:8000

## License

Free to use for personal and commercial projects.
"""
    
    readme_path = os.path.join(website_dir, "README.md")
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    print(f"✅ Updated: README.md")
    
    return True

def fix_city_page_links():
    """Fix links in city pages for GitHub Pages deployment."""
    
    print("\n🔗 Fixing city page links for GitHub Pages...")
    
    website_dir = os.path.dirname(os.path.abspath(__file__))
    cities_dir = os.path.join(website_dir, "cities")
    
    if not os.path.exists(cities_dir):
        print("❌ Cities directory not found")
        return False
    
    city_files = [f for f in os.listdir(cities_dir) if f.endswith('.html')]
    
    fixes_applied = 0
    
    for city_file in city_files:
        file_path = os.path.join(cities_dir, city_file)
        
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Fix back to home link for GitHub Pages
        # Change "../index.html" to "/travel-website/index.html" or "/index.html"
        old_link = 'href="../index.html"'
        new_link = 'href="/travel-website/index.html"'
        
        if old_link in content:
            content = content.replace(old_link, new_link)
            fixes_applied += 1
            print(f"✅ Fixed back link in {city_file}")
        
        # Fix CSS link if needed
        old_css = 'href="../style.css"'
        new_css = 'href="/travel-website/style.css"'
        
        if old_css in content:
            content = content.replace(old_css, new_css)
            fixes_applied += 1
            print(f"✅ Fixed CSS link in {city_file}")
        
        # Write back
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
    
    # Also fix main page if needed
    main_page = os.path.join(website_dir, "index.html")
    if os.path.exists(main_page):
        with open(main_page, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Fix city page links in main page
        for city_file in city_files:
            city_name = city_file.replace('.html', '')
            old_city_link = f'href="cities/{city_file}"'
            new_city_link = f'href="/travel-website/cities/{city_file}"'
            
            if old_city_link in content:
                content = content.replace(old_city_link, new_city_link)
                fixes_applied += 1
                print(f"✅ Fixed {city_name} link in main page")
        
        with open(main_page, 'w', encoding='utf-8') as f:
            f.write(content)
    
    print(f"\n🔧 Applied {fixes_applied} link fixes for GitHub Pages")
    return fixes_applied > 0

def create_deployment_instructions():
    """Create deployment instructions for GitHub Pages."""
    
    print("\n🚀 Creating deployment instructions...")
    
    instructions = """# GitHub Pages Deployment Instructions

## Current Issue
Your site is deployed at: https://fli-rpx.github.io/travel-website/
But city pages return 404: https://fli-rpx.github.io/travel-website/cities/guangzhou.html

## Solution

### Step 1: Update GitHub Repository
```bash
cd /Users/fudongli/clawd/travel-website

# Add all files
git add .

# Commit changes
git commit -m "Fix GitHub Pages deployment"

# Push to GitHub
git push origin main
```

### Step 2: Enable GitHub Pages (if not already)
1. Go to: https://github.com/fli-rpx/travel-website/settings/pages
2. Source: Deploy from branch
3. Branch: main
4. Folder: / (root)
5. Save

### Step 3: Wait for Deployment
GitHub Pages takes 1-2 minutes to deploy after push.

### Step 4: Test
1. Main page: https://fli-rpx.github.io/travel-website/
2. City page: https://fli-rpx.github.io/travel-website/cities/guangzhou.html

## Alternative: Use Relative Paths (Better)

If absolute paths don't work, use relative paths:

### In city pages (cities/*.html):
Change: `href="../index.html"`
To: `href="../index.html"` (keep as is for relative)

### In main page (index.html):
Change: `href="cities/guangzhou.html"`
To: `href="./cities/guangzhou.html"` (add ./ for clarity)

## Files Created for GitHub Pages:
1. `.nojekyll` - Disables Jekyll processing
2. `.gitignore` - Ignores logs and config files
3. Updated `README.md` - Documentation

## Testing Locally Before Push
```bash
cd /Users/fudongli/clawd/travel-website
python3 -m http.server 8000
# Open: http://localhost:8000/cities/guangzhou.html
```

## Need Help?
Check GitHub Pages documentation: https://docs.github.com/en/pages
"""
    
    instructions_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "GITHUB_PAGES_FIX.md")
    with open(instructions_file, 'w', encoding='utf-8') as f:
        f.write(instructions)
    
    print(f"✅ Created: GITHUB_PAGES_FIX.md")
    return instructions_file

def main():
    """Main fix function."""
    
    print("🔧 Fixing GitHub Pages deployment...")
    
    # Check current structure
    if not check_github_pages_structure():
        print("\n❌ Website structure has issues")
        return
    
    # Create config files
    create_github_pages_config()
    
    # Fix links
    fix_city_page_links()
    
    # Create instructions
    instructions_file = create_deployment_instructions()
    
    print("\n" + "=" * 70)
    print("✅ GITHUB PAGES FIX COMPLETE")
    print("=" * 70)
    
    print("\n📋 Next Steps:")
    print("1. Run: cd /Users/fudongli/clawd/travel-website")
    print("2. Run: git add .")
    print("3. Run: git commit -m 'Fix GitHub Pages deployment'")
    print("4. Run: git push origin main")
    print("5. Wait 1-2 minutes for GitHub Pages to update")
    print("6. Test: https://fli-rpx.github.io/travel-website/cities/guangzhou.html")
    
    print(f"\n📄 Complete instructions: {instructions_file}")
    
    print("\n💡 Quick test command:")
    print("python3 -m http.server 8000")
    print("# Then open: http://localhost:8000/cities/guangzhou.html")

if __name__ == "__main__":
    main()